CREATE DATABASE LIBRARY;
USE LIBRARY;

CREATE TABLE User (
  ID VARCHAR(255) PRIMARY KEY,
  Fname VARCHAR(255) NOT NULL,
  Lname VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Phone_Number INT,
  Account VARCHAR(255) NOT NULL, 
  Password VARCHAR(255) NOT NULL,
  Balance INT,
  Club_ID INT,
  Address VARCHAR(255),
  Recent_search VARCHAR(255)
);

CREATE TABLE Admin (
  ID VARCHAR(255) PRIMARY KEY,
  Fname VARCHAR(255) NOT NULL,
  Lname VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  Account VARCHAR(255) NOT NULL, 
  Password VARCHAR(255) NOT NULL,
  Phone_Number INT
);

CREATE TABLE Book (
  ID_Book INT PRIMARY KEY ,
  Title VARCHAR(255) NOT NULL,
  Author VARCHAR(255) NOT NULL,
  Publisher VARCHAR(255) NOT NULL,
  YearPublish VARCHAR(255) NOT NULL,
  Tag VARCHAR(255),
  Main_Category VARCHAR(255) NOT NULL,
  ISBN VARCHAR(255) NOT NULL UNIQUE,
  Quantity INT NOT NULL
);

CREATE TABLE Room (
  ID_Room INT PRIMARY KEY,
  Location VARCHAR(255) NOT NULL,
  Availability VARCHAR(255) NOT NULL
);

CREATE TABLE Club (
  Club_ID INT PRIMARY KEY,
  Club_name VARCHAR(255) NOT NULL,
  Owner_ID VARCHAR(255) NOT NULL,
  FOREIGN KEY (Owner_ID) REFERENCES User(ID)
);

CREATE TABLE Review (
  ID_Report INT PRIMARY KEY,
  ID_User VARCHAR(255) NOT NULL,
  ID_Book INT NOT NULL,
  Rating VARCHAR(255) NOT NULL,
  Comment VARCHAR(255),
  Date_Time DATETIME NOT NULL,
  FOREIGN KEY (ID_User) REFERENCES User(ID),
  FOREIGN KEY (ID_Book) REFERENCES Book(ID_Book)
);

CREATE TABLE Rent (
  ID_Rent INT PRIMARY KEY,
  ID_User VARCHAR(255) NOT NULL, 
  ID_Book INT NOT NULL,
  Issue_Date DATETIME NOT NULL,
  Return_Date DATETIME,
  FOREIGN KEY (ID_User) REFERENCES User(ID),
  FOREIGN KEY (ID_Book) REFERENCES Book(ID_Book)
);

CREATE TABLE Room_Booking (
  ID INT PRIMARY KEY,
  ID_Room INT NOT NULL,
  ID_User VARCHAR(255) NOT NULL,
  Date_Time DATETIME NOT NULL,
  Payment_method VARCHAR(255) NOT NULL,
  Duration VARCHAR(255) NOT NULL,
  FOREIGN KEY (ID_Room) REFERENCES Room(ID_Room),
  FOREIGN KEY (ID_User) REFERENCES User(ID)
);

CREATE TABLE Forum_Post (
  ID_Post INT PRIMARY KEY,
  ID_User VARCHAR(255) NOT NULL, 
  Content VARCHAR(255) NOT NULL,
  Date_Time DATETIME NOT NULL,
  FOREIGN KEY (ID_User) REFERENCES User(ID)
);

CREATE TABLE Forum_Comment (
  ID_Comment INT PRIMARY KEY,
  ID_Post INT NOT NULL,
  Content VARCHAR(255) NOT NULL,
  Date_Time DATETIME NOT NULL,
  FOREIGN KEY (ID_Post) REFERENCES Forum_Post(ID_Post)
);
